### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Zelecktor** [RansomF4ck/MODRIG#1]
Using Microsoft Visual Studios 2017

Error starting from here (sorry, but i got mvs in spanish)

```
3>C:\Users\Admin\Desktop\MODRIG-master\src\xmrig.cpp(110): error C2078: hay demasiados inicializadores
3>App_win.cpp
3>Cpu_win.cpp
3>Mem_win.cpp
3>Platform_win.cpp
3>Cpu.cpp
3>C:\Users\Admin\Desktop\MODRIG-master\src\Cpu.cpp(14): error C2511: 'int Cpu::optimalThreadsCount(int,bool,int)': la función miembro sobrecargada no se ha encontrado en 'Cpu'
3>c:\users\admin\desktop\modrig-master\src\Cpu.h(5): note: vea la declaración de 'Cpu'
3>CryptoNight.cpp
3>C:\Users\Admin\Desktop\MODRIG-master\src\crypto\CryptoNight.cpp(64): error C2039: 'ALGO_CRYPTONIGHT_LITE': no es un miembro de 'Options'
3>C:\Users\Admin\Desktop\MODRIG-master\src\Options.h(12): note: vea la declaración de 'Options'
3>C:\Users\Admin\Desktop\MODRIG-master\src\crypto\CryptoNight.cpp(64): error C2065: 'ALGO_CRYPTONIGHT_LITE': identificador no declarado
3>C:\Users\Admin\Desktop\MODRIG-master\src\crypto\CryptoNight.cpp(64): error C2789: 'index': se debe inicializar un objeto de tipo
3>C:\Users\Admin\Desktop\MODRIG-master\src\crypto\CryptoNight.cpp(64): note: vea la declaración de 'index'
3>C:\Users\Admin\Desktop\MODRIG-master\src\crypto\CryptoNight.cpp(87): error C2039: 'ALGO_CRYPTONIGHT_LITE': no es un miembro de 'Options'
3>C:\Users\Admin\Desktop\MODRIG-master\src\Options.h(12): note: vea la declaración de 'Options'
3>C:\Users\Admin\Desktop\MODRIG-master\src\crypto\CryptoNight.cpp(87): error C2065: 'ALGO_CRYPTONIGHT_LITE': identificador no declarado
3>C:\Users\Admin\Desktop\MODRIG-master\src\crypto\CryptoNight.cpp(87): error C2660: 'memcmp': la función no acepta 2 argumentos
3>Httpd.cpp
3>Compilación del proyecto "xmrig.vcxproj" terminada -- ERROR.
4>------ Operación Compilar iniciada: proyecto: ALL_BUILD, configuración: Release x64 ------
4>Building Custom Rule C:/Users/Admin/Desktop/MODRIG-master/CMakeLists.txt
4>CMake does not need to re-run because C:/Users/Admin/Desktop/MODRIG-master/build/CMakeFiles/generate.stamp is up-to-date.
========== Compilar: 3 correctos, 1 incorrectos, 0 actualizados, 0 omitidos ==========
```

**Comment by Zelecktor** [comment]
Here are my steps:

1. Download your reposioty
2. Make the solution using Cmake 3.9.6-win64

- oppen cmd, go to path of MODRIG-master/build
- type this command:

```
cmake .. -G "Visual Studio 15 2017 Win64" -DUV_INCLUDE_DIR="C:\Users\Admin\Desktop\xmrig-deps-2.2\msvc2017\libuv\x64\include" -DUV_LIBRARY="C:\Users\Admin\Desktop\xmrig-deps-2.2\msvc2017\libuv\x64\lib\libuv.lib" -DMHD_INCLUDE_DIR="C:\Users\Admin\Desktop\xmrig-deps-2.2\msvc2017\libmicrohttpd\x64\include" -DMHD_LIBRARY="C:\Users\Admin\Desktop\xmrig-deps-2.2\msvc2017\libmicrohttpd\x64\lib\libmicrohttpd.lib"
```

3. go to build folder (where is the solution) and oppen `xmrig.sln` on visual studios.

- swich build compiler to "release"
- Build

All fine, some warnings message but after step 3 started "error". I posted from the first error till the end of building.

**Comment by RansomF4ck** [comment]
Hi, Zelecktor. First build original xmrig. After building replace src folder to my. Build without MHD and if have some warnings - change warning level, remove buffer-overload check and read https://forum.antichat.ru/threads/umenshenie-razmera-si-programmy-na-primere-visual-studio.270620/ (Step one and two)

**Comment by Zelecktor** [comment]
Let me see if i understand.
Cmake is to make the solution for visual studios, so i cmake without this
```
-DMHD_INCLUDE_DIR="C:\Users\Admin\Desktop\xmrig-deps-2.2\msvc2017\libmicrohttpd\x64\include" -DMHD_LIBRARY="C:\Users\Admin\Desktop\xmrig-deps-2.2\msvc2017\libmicrohttpd\x64\lib\libmicrohttpd.lib"
```

To build,  on visual studios, first i build the original xmrig, then on the directory change only your src folder and then re-build

Thats all?
Thanks very much.

PD: the forum is in russian and the translation sucks for english and spanish. I dont have the same options on visual studios for optimizing c++ builder. If you have another guide or video i will apreciate (dont think that im lazy but i have been googling and searching videos for hours and i couldnt find anything)

**Comment by RansomF4ck** [comment]
Okay, i am write mini-wiki.
To use my full version:
1. Download original xmrig and build without MHD
2. Select in studio "Release", x32, build
3. Replace **src** dir with my mod
4. Build (if you get some error, change warning level)

Short info i am send to you email. Anti script-kiddy ;-), don`t want share to public, many create malware.

**Comment by Zelecktor** [comment]
Thanks very much for the info. Really apreciate.
