### ISSUE TITLE
Runs but no mining done

### ISSUE THREAD

**Issue by Zambi9** [RansomF4ck/MODRIG#2]
I followed the mini wiki, fixed a few "anti-script kiddies" errors in the code and managed to get the thing built and run.

It moves itself to the appdata/roaming folder, and I can see it in the task manager named "Windows system", it autostarts on reboot, but it doesn't seem to do any mining. It stays on close to 0% CPU and I don't see any mining done in the pool page. That's the same pool I used with the original xmrig.

I encoded my pool url and wallet with base64 encoder, and pasted them in xmrig.cpp so I think this part is correct. 

Any ideas?
Thank you.

**Comment by Zelecktor** [comment]
Yeah, got the same issue. After building, the miner doesnt start.
Then i also fix some scripts with the debug manager to get fully working but miner is not mining.
I compared both version with the original xmrig (algorithm and pool conection) but all seems to be ok, its the same script.

PD: i didnt received your e-mail, if you can re-send it would be great. Thanks in advance
zeleck.ro01@gmail.com
Or try my institution e-mail (more secure)
claudio.rodriguezal@correoaiep.cl

**Comment by RansomF4ck** [comment]
Hi. If u run Taskmgr or other utilities - mining process stop. In code have some errors, I am not give fully works code, I am don`t want to give easy way for create malware.
Message re-send to u e-mail.
